---
# Compute: EC2 instance creation
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Launch or get EC2 instance for Kafka (VM-1)
      amazon.aws.ec2_instance:
        name: VM-1-Kafka
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        vpc_subnet_id: "{{ private_subnet.subnet.id }}"
        security_group: "{{ sg_kafka.group_id }}"
        region: "{{ region }}"
        wait: yes
        tags:
          Name: plant-monitoring-vm-1-kafka
        state: present
      register: kafka_instance

    - name: Launch or get EC2 instance for MongoDB (VM-2)
      amazon.aws.ec2_instance:
        name: VM-2-MongoDB
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        vpc_subnet_id: "{{ private_subnet.subnet.id }}"
        security_group: "{{ sg_mongodb.group_id }}"
        region: "{{ region }}"
        wait: yes
        tags:
          Name: plant-monitoring-vm-2-mongodb
        state: present
      register: mongodb_instance

    - name: Launch or get EC2 instance for Processor (VM-3)
      amazon.aws.ec2_instance:
        name: VM-3-Processor
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        vpc_subnet_id: "{{ private_subnet.subnet.id }}"
        security_group: "{{ sg_processor.group_id }}"
        region: "{{ region }}"
        wait: yes
        tags:
          Name: plant-monitoring-vm-3-processor
        state: present
      register: processor_instance

    - name: Launch or get EC2 instance for Home Assistant (VM-4)
      amazon.aws.ec2_instance:
        name: VM-4-HomeAssistant
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami }}"
        vpc_subnet_id: "{{ public_subnet.subnet.id }}"
        security_group: "{{ sg_homeassistant.group_id }}"
        region: "{{ region }}"
        wait: yes
        tags:
          Name: plant-monitoring-vm-4-homeassistant
        state: present
      register: ha_instance
