version: '3.8'
services:
  mongodb:
    image: mongo:6.0.4
    hostname: mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=AdminPass123!
      - MONGO_INITDB_DATABASE=plant_monitoring
    restart: unless-stopped
    mem_limit: 400m  # Memory limit for t2.micro
    user: "999:999"  # MongoDB user for security
    command: >
      mongod 
      --wiredTigerCacheSizeGB 0.25 
      --quiet
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
