---
# Deploy Home Assistant and Plant Sensors to VM-4
- hosts: homeassistant_vm
  become: yes
  vars:
    app_dir: /opt/apps/homeassistant
    ansible_user: ubuntu
  tasks:
    - name: Create Home Assistant application directories
      file:
        path: "{{ item }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      loop:
        - "{{ app_dir }}"
        - "{{ app_dir }}/plant-sensors"
        - "{{ app_dir }}/mosquitto/config"

    - name: Copy Home Assistant docker-compose.yml with IP substitution
      template:
        src: ../applications/vm-4-homeassistant/docker-compose.yml
        dest: "{{ app_dir }}/docker-compose.yml"
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      vars:
        kafka_vm_private_ip: "{{ hostvars[groups['kafka_vm'][0]]['ansible_default_ipv4']['address'] }}"

    - name: Copy Plant Sensor application files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      loop:
        - { src: '../applications/vm-4-homeassistant/plant-sensors/sensor.js', dest: '{{ app_dir }}/plant-sensors/sensor.js' }
        - { src: '../applications/vm-4-homeassistant/plant-sensors/package.json', dest: '{{ app_dir }}/plant-sensors/package.json' }
        - { src: '../applications/vm-4-homeassistant/plant-sensors/Dockerfile', dest: '{{ app_dir }}/plant-sensors/Dockerfile' }

    - name: Copy Mosquitto configuration
      copy:
        src: ../applications/vm-4-homeassistant/mosquitto/config/mosquitto.conf
        dest: "{{ app_dir }}/mosquitto/config/mosquitto.conf"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Wait for Kafka to be available
      wait_for:
        host: "{{ hostvars[groups['kafka_vm'][0]]['ansible_default_ipv4']['address'] }}"
        port: 9092
        delay: 10
        timeout: 300

    - name: Stop any existing Home Assistant containers
      command: docker compose down
      args:
        chdir: "{{ app_dir }}"
      become_user: ubuntu
      ignore_errors: yes

    - name: Build and start Home Assistant services
      command: docker compose up -d --build
      args:
        chdir: "{{ app_dir }}"
      become_user: ubuntu

    - name: Wait for Home Assistant to be ready
      wait_for:
        port: 8123
        host: "{{ ansible_default_ipv4.address }}"
        delay: 60
        timeout: 600

    - name: Wait for MQTT broker to be ready
      wait_for:
        port: 1883
        host: "{{ ansible_default_ipv4.address }}"
        delay: 30
        timeout: 300

    - name: Check Home Assistant container status
      command: docker compose ps
      args:
        chdir: "{{ app_dir }}"
      become_user: ubuntu
      register: ha_status

    - name: Display Home Assistant status
      debug:
        msg: "Home Assistant service status: {{ ha_status.stdout_lines }}"

    - name: Show Plant Sensor logs
      command: docker compose logs --tail=10 plant-sensor-001
      args:
        chdir: "{{ app_dir }}"
      become_user: ubuntu
      register: sensor_logs

    - name: Display recent Sensor logs
      debug:
        msg: "Recent Plant Sensor logs: {{ sensor_logs.stdout_lines }}"

    - name: Display Home Assistant access information
      debug:
        msg: 
          - "Home Assistant is ready!"
          - "Access the dashboard at: http://{{ ansible_default_ipv4.address }}:8123"
          - "MQTT broker is running on port 1883"
          - "Plant sensors are sending data to Kafka"