---
# Networking: VPC, subnets, IGW, NAT, route tables
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create or get VPC
      amazon.aws.ec2_vpc_net:
        name: plant-monitoring-vpc
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ region }}"
        tags:
          Name: plant-monitoring-vpc
        state: present
      register: vpc

    - name: Create or get public subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ public_subnet_cidr }}"
        map_public: yes
        region: "{{ region }}"
        tags:
          Name: plant-monitoring-public-subnet
        state: present
      register: public_subnet

    - name: Create or get private subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ private_subnet_cidr }}"
        region: "{{ region }}"
        tags:
          Name: plant-monitoring-private-subnet
        state: present
      register: private_subnet

    - name: Create or get Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: plant-monitoring-igw
        state: present
      register: igw


    - name: Create or get public route table (with IGW route)
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: plant-monitoring-public-rt
        routes:
          - dest: "0.0.0.0/0"
            gateway_id: "{{ igw.gateway_id }}"
        subnets:
          - "{{ public_subnet.subnet.id }}"
        state: present
      register: public_rt

