---
# Network Endpoints: EIPs, NAT Gateway, and Private Route Table
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    # Look up VPC and subnets to get required IDs
    - name: Lookup VPC by CIDR
      amazon.aws.ec2_vpc_net_info:
        region: "{{ region }}"
        filters:
          cidr: "{{ vpc_cidr }}"
      register: vpc_lookup

    - name: Set vpc_id fact
      set_fact:
        vpc_id: "{{ vpc_lookup.vpcs[0].id }}"
      when: vpc_lookup.vpcs is defined and vpc_lookup.vpcs|length > 0

    - name: Lookup public subnet
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
          cidr-block: "{{ public_subnet_cidr }}"
      register: public_subnet_lookup
      when: vpc_id is defined

    - name: Set public_subnet_id fact
      set_fact:
        public_subnet_id: "{{ public_subnet_lookup.subnets[0].id }}"
      when: public_subnet_lookup.subnets is defined and public_subnet_lookup.subnets|length > 0

    - name: Lookup private subnet
      amazon.aws.ec2_vpc_subnet_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
          cidr-block: "{{ private_subnet_cidr }}"
      register: private_subnet_lookup
      when: vpc_id is defined

    - name: Set private_subnet_id fact
      set_fact:
        private_subnet_id: "{{ private_subnet_lookup.subnets[0].id }}"
      when: private_subnet_lookup.subnets is defined and private_subnet_lookup.subnets|length > 0

    - name: Find existing EIP for NAT Gateway by tag
      amazon.aws.ec2_eip_info:
        region: "{{ region }}"
        filters:
          tag:Name: "plant-monitoring-nat-eip"
      register: eip_info

    - name: Set NAT EIP allocation_id from existing tagged EIP
      set_fact:
        nat_eip_allocation_id: "{{ eip_info.addresses[0].allocation_id }}"
      when: eip_info.addresses is defined and eip_info.addresses|length > 0

    - name: Allocate new Elastic IP for NAT Gateway if tagged EIP doesn't exist
      amazon.aws.ec2_eip:
        in_vpc: true
        region: "{{ region }}"
        tags:
          Name: plant-monitoring-nat-eip
        state: present
      register: nat_eip
      when: nat_eip_allocation_id is not defined

    - name: Set NAT EIP allocation_id from newly created EIP
      set_fact:
        nat_eip_allocation_id: "{{ nat_eip.allocation_id }}"
      when: nat_eip_allocation_id is not defined and nat_eip is defined

    # NAT Gateway lookup and creation (moved from networking.yml)
    - name: Find existing plant-monitoring NAT Gateway by tag
      amazon.aws.ec2_vpc_nat_gateway_info:
        region: "{{ region }}"
        filters:
          tag:Name: "plant-monitoring-nat-gw"
          state: "available"
      register: nat_gw_info

    - name: Set NAT Gateway ID from existing plant-monitoring NAT Gateway
      set_fact:
        nat_gw_id: "{{ nat_gw_info.nat_gateways[0].nat_gateway_id }}"
      when: nat_gw_info.nat_gateways is defined and nat_gw_info.nat_gateways|length > 0

    - name: Create NAT Gateway in public subnet if plant-monitoring NAT Gateway doesn't exist
      amazon.aws.ec2_vpc_nat_gateway:
        subnet_id: "{{ public_subnet_id }}"
        allocation_id: "{{ nat_eip_allocation_id }}"
        region: "{{ region }}"
        tags:
          Name: plant-monitoring-nat-gw
        state: present
      register: nat_gw
      when: nat_gw_id is not defined and nat_eip_allocation_id is defined

    - name: Set NAT Gateway ID from newly created NAT Gateway
      set_fact:
        nat_gw_id: "{{ nat_gw.nat_gateway_id }}"
      when: nat_gw is defined and nat_gw.nat_gateway_id is defined

    - name: Wait for NAT Gateway to be available before creating routes
      amazon.aws.ec2_vpc_nat_gateway_info:
        region: "{{ region }}"
        nat_gateway_ids:
          - "{{ nat_gw_id }}"
      register: nat_gw_status
      until: nat_gw_status.result is defined and nat_gw_status.result|length > 0 and nat_gw_status.result[0].state == 'available'
      retries: 30
      delay: 10
      when: nat_gw_id is defined

    - name: Verify NAT Gateway exists and is available
      debug:
        msg: "NAT Gateway {{ nat_gw_id }} is available. State: {{ nat_gw_status.result[0].state }}"
      when: nat_gw_id is defined and nat_gw_status.result is defined and nat_gw_status.result|length > 0

    # Private route table (must be created after NAT Gateway is available)
    - name: Create or get private route table (with NAT Gateway route)
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        tags:
          Name: plant-monitoring-private-rt
        routes:
          - dest: "0.0.0.0/0"
            nat_gateway_id: "{{ nat_gw_id }}"
        subnets:
          - "{{ private_subnet_id }}"
        state: present
      register: private_rt
      when: nat_gw_id is defined and private_subnet_id is defined and vpc_id is defined

    - name: Find existing EIP for Home Assistant by tag
      amazon.aws.ec2_eip_info:
        region: "{{ region }}"
        filters:
          tag:Name: "plant-monitoring-ha-eip"
      register: ha_eip_info

    - name: Set Home Assistant EIP public_ip from existing tagged EIP
      set_fact:
        ha_eip_public_ip: "{{ ha_eip_info.addresses[0].public_ip }}"
        ha_eip_allocation_id: "{{ ha_eip_info.addresses[0].allocation_id }}"
      when: ha_eip_info.addresses is defined and ha_eip_info.addresses|length > 0

    - name: Allocate new Elastic IP for Home Assistant if tagged EIP doesn't exist
      amazon.aws.ec2_eip:
        in_vpc: true
        region: "{{ region }}"
        tags:
          Name: plant-monitoring-ha-eip
        state: present
      register: ha_eip_new
      when: ha_eip_public_ip is not defined

    - name: Set Home Assistant EIP details from newly created EIP
      set_fact:
        ha_eip_public_ip: "{{ ha_eip_new.public_ip }}"
        ha_eip_allocation_id: "{{ ha_eip_new.allocation_id }}"
      when: ha_eip_public_ip is not defined and ha_eip_new is defined

    # Lookup EC2 instances by name
    - name: Lookup Home Assistant instance
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          tag:Name: "VM-4-HomeAssistant"
          instance-state-name: "running"
      register: ha_instance_lookup

    - name: Lookup all EC2 instances for debug output
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ vpc_id }}"
          instance-state-name: "running"
      register: all_instances_lookup

    - name: Set instance facts for reference
      set_fact:
        kafka_instance_info: "{{ all_instances_lookup.instances | selectattr('tags.Name', 'equalto', 'VM-1-Kafka') | first }}"
        mongodb_instance_info: "{{ all_instances_lookup.instances | selectattr('tags.Name', 'equalto', 'VM-2-MongoDB') | first }}"
        processor_instance_info: "{{ all_instances_lookup.instances | selectattr('tags.Name', 'equalto', 'VM-3-Processor') | first }}"
        ha_instance_info: "{{ ha_instance_lookup.instances[0] }}"
      when: ha_instance_lookup.instances is defined and ha_instance_lookup.instances|length > 0

    - name: Wait for Home Assistant instance to be running
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        instance_ids:
          - "{{ ha_instance_info.instance_id }}"
      register: ha_instance_state
      until: ha_instance_state.instances[0].state.name == 'running'
      retries: 12
      delay: 10
      when: ha_instance_info is defined

    - name: Associate Elastic IP with Home Assistant instance
      community.aws.ec2_eip:
        region: "{{ region }}"
        public_ip: "{{ ha_eip_public_ip }}"
        device_id: "{{ ha_instance_info.network_interfaces[0].network_interface_id }}"
        private_ip_address: "{{ ha_instance_info.private_ip_address }}"
        in_vpc: true
        state: present
      when: ha_eip_public_ip is defined and ha_instance_info is defined

    - name: Show instance details
      debug:
        msg:
          - "Kafka: {{ kafka_instance_info.private_ip_address | default('Not found') }}"
          - "MongoDB: {{ mongodb_instance_info.private_ip_address | default('Not found') }}"
          - "Processor: {{ processor_instance_info.private_ip_address | default('Not found') }}"
          - "Home Assistant: {{ ha_instance_info.private_ip_address | default('Not found') }} (Elastic IP: {{ ha_eip_public_ip | default('Not assigned') }})"
      when: all_instances_lookup.instances is defined
