#!/bin/bash
# image-cost-analysis.sh
# Analyze data transfer costs for different image strategies

echo "🔍 Container Image Data Transfer Cost Analysis"
echo "=============================================="
echo ""

echo "📊 CURRENT DEPLOYMENT IMAGES:"
echo "-----------------------------"
echo "Large Images (>100MB):"
echo "  • homeassistant/home-assistant:2024.1.0  ~400MB"
echo "  • mongo:6.0.4                           ~150MB"
echo "  • confluentinc/cp-kafka:7.4.0           ~200MB"
echo ""
echo "Small Images (<50MB):"
echo "  • eclipse-mosquitto:2.0.18              ~30MB"
echo "  • python:3.9-alpine                     ~45MB"
echo ""
echo "AWS Optimized Images (FREE):"
echo "  • public.ecr.aws/ebs-csi-driver/*       FREE (AWS Public ECR)"
echo "  • registry.k8s.io/ingress-nginx/*       FREE (Kubernetes registry)"
echo ""

echo "💰 COST SCENARIOS (5-node cluster):"
echo "-----------------------------------"
echo ""
echo "Scenario 1: Docker Hub Only (Current)"
echo "  • Per deployment: (400+150+200+30+45) × 5 nodes = ~4.1GB"
echo "  • AWS Free Tier: 1GB/month"
echo "  • Result: Exceeds limit on first deployment! 💸"
echo ""
echo "Scenario 2: Cache Large Images to ECR + VPC Endpoints"
echo "  • First deployment: 4.1GB (one-time setup)"
echo "  • Subsequent deployments: ~150MB (only small images)"
echo "  • VPC endpoints: Pull large images through AWS private network"
echo "  • Result: 95% reduction after first deployment ✅"
echo ""
echo "Scenario 3: Smart Hybrid (RECOMMENDED)"
echo "  • Cache only 3 largest images (750MB) to ECR"
echo "  • Keep small images (75MB) on Docker Hub"  
echo "  • Per deployment after caching: 75MB × 5 = 375MB"
echo "  • Result: Stay within free tier limits! 🎯"
echo ""

echo "🎯 RECOMMENDED STRATEGY:"
echo "========================"
echo "✅ Cache these to ECR (data transfer savings):"
echo "   • homeassistant/home-assistant (400MB → VPC endpoint)"
echo "   • mongo (150MB → VPC endpoint)"
echo "   • confluentinc/cp-kafka (200MB → VPC endpoint)"
echo ""
echo "⚡ Keep these on Docker Hub (cost-effective):"
echo "   • eclipse-mosquitto (30MB - minimal impact)"
echo "   • python:3.9-alpine (45MB - minimal impact)"
echo ""
echo "🆓 Use AWS optimized when available:"
echo "   • public.ecr.aws/* (no data transfer charges)"
echo "   • registry.k8s.io/* (Kubernetes registry)"
echo ""

echo "📈 SAVINGS CALCULATION:"
echo "======================="
echo "Before optimization:"
echo "  • 4.1GB × $0.09/GB = $0.37 per deployment"
echo "  • Multiple deployments = $1.11+ (exceeds free tier)"
echo ""
echo "After smart caching:"
echo "  • Initial setup: $0.37 (one-time)"
echo "  • Ongoing deployments: $0.03 each (95% savings)"
echo "  • Monthly cost: <$0.50 (well within free tier)"
echo ""

echo "💡 KEY INSIGHT:"
echo "==============="
echo "Don't cache small images - Docker Hub is more cost-effective"
echo "for images under 100MB when accounting for ECR storage costs!"
echo ""
echo "🚀 Implementation: Run smart-image-cache.sh"
echo "✅ Only caches images where ECR provides clear benefit"